server:
  port: 8082


spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/paas_db?useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 12345
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 30
      min-idle: 3
      initial-size: 3
      validation-query: select 1
      max-wait: 5000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-pattern:
          - /druid/*

kubernetes:
  namespace:
    default: default

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

order:
  cancel:
    delay:
      time: 10000 # ms 15minute
    method: 1 # 1.  jdk delay Queue  2. Netty HashWheelTimer
