server:
  port: 8082


spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/paas_db?useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: 12345
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3307/paas_db?useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://localhost:3308/paas_db?useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      timeout: 5000
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: simple

kubernetes:
  namespace:
    default: default

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

order:
  cancel:
    delay:
      time: 10000 # ms 15minute
    method: 5 # 1.  jdk delay Queue  2. Netty HashWheelTimer
              # 3. JRedis delay queue 4. StringRedisTemplate delay queue
              # 5. Rabbitmq Dead Queue

redis:
  host: 127.0.0.1
  port: 6379
  password:
  jedis:
    timeout: 5000
    pool:
      max-idle: 8
      max-wait: -1
      min-idle: 0

